'use client'

import React, { createContext, useContext, useState } from 'react'

type Language = 'zh' | 'en'

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar sections
    'nav.home': '首頁',
    'nav.news': '最新消息',
    'nav.registration': '會議報名',
    'nav.registration.timeline': '報名時程',
    'nav.registration.fees': '報名費用',
    'nav.registration.method': '報名方式',
    'nav.registration.notice': '報名須知',
    'nav.registration.go': '前往報名',
    'nav.submission': '論文發表',
    'nav.submission.guide': '投稿說明',
    'nav.submission.guidelines': '發表注意事項',
    'nav.submission.go': '前往投稿',
    'nav.sponsors': '參展贊助',
    'nav.sponsors.units': '參展及贊助單位',
    'nav.about': '會議資訊',
    'nav.about.intro': '會議介紹',
    'nav.about.transport': '交通資訊',
    'nav.about.contact': '聯絡我們',
    'nav.3s': '3S創客競賽',
    'nav.3s.rules': '競賽細則',
    // User area
    'auth.login': '會員登入',
    'auth.loginRegister': '會員登入 / 註冊',
    'auth.member': '會員中心',
    'auth.loggedInAs': '已登入為',
    'auth.logout': '登出',
    'auth.loginError': '帳號或密碼輸入錯誤，請再試一次。',
    // Login page
    'login.title': '登入 SG44',
    'login.email': 'Email',
    'login.password': '密碼',
    'login.forgotPassword': '忘記密碼？',
    'login.submit': '登入',
    'login.submitting': '登入中...',
    'login.noAccount': '還沒有帳號？',
    'login.registerNow': '立即註冊',
    'login.error.default': '登入失敗，請檢查帳號密碼',
    'login.error.credentials': '登入失敗，請確認您的信箱與密碼是否完全正確。',
    // Register page
    'register.title': '註冊會員帳號',
    'register.name': '姓名',
    'register.email': 'Email',
    'register.password': '密碼',
    'register.password.hint': '密碼至少需 6 碼',
    'register.confirmPassword': '確認密碼',
    'register.organization': '所屬單位',
    'register.organization.hint': '學校或公司',
    'register.jobTitle': '職稱',
    'register.jobTitle.hint': '如: 教授、學生',
    'register.phone': '手機號碼',
    'register.birthday': '出生年月日',
    'register.gender': '性別 (選填)',
    'register.gender.placeholder': '請選擇',
    'register.gender.male': '男',
    'register.gender.female': '女',
    'register.gender.other': '不透露/其他',
    'register.details': '詳細資料',
    'register.submit': '註冊帳號',
    'register.submitting': '註冊中...',
    'register.haveAccount': '已經有帳號了嗎？',
    'register.login': '登入',
    'register.success.title': '註冊成功！',
    'register.success.msg': '驗證信件已發送至您的信箱，請查收並點擊連結啟用帳號。',
    'register.error.exists': '這個信箱已經被註冊過了，請直接登入或使用忘記密碼。',
    'register.error.validation': '部分資料格式不符，請檢查輸入內容是否完整。',
    // General Validation
    'validation.required': '此欄位為必填',
    'validation.email': '請輸入正確的 Email 格式',
    'validation.passwordMatch': '兩次密碼不一致',
    // SG44 Register form
    'sg44.title': '研討會報名系統',
    'sg44.subtitle': 'Conference Registration',
    'sg44.desc': '歡迎報名【第44屆測量及空間資訊研討會】。大會將於 2026.08.20 ~ 2026.08.21 假國立政治大學舉辦。',
    'sg44.payment.info': '繳費資訊',
    'sg44.payment.method': '繳費方式',
    'sg44.payment.bank': '銀行轉帳 (808 玉山銀行)',
    'sg44.step1': '1. 報名費與票種選擇',
    'sg44.step2': '2. 基本資料',
    'sg44.step3': '3. 會議參與資訊',
    'sg44.step4': '4. 繳費對帳資訊',
    'sg44.step5': '5. 膳食與活動意願',
    'sg44.submit': '確認資料無誤並送出報名表',
    'sg44.submit.submitting': '報名資料處理中...',
    // Abstract Submit
    'abstract.submit.title': '摘要投稿系統',
    'abstract.submit.subtitle': 'Abstract Submission',
    'abstract.submit.desc': '歡迎投稿第44屆測量及空間資訊研討會。請依序填寫作者資訊、投稿分類與摘要內容。',
    'abstract.submit.closed.title': '摘要投稿已截止',
    'abstract.submit.closed.desc': '目前投稿系統已關閉，感謝您的參與。',
    'abstract.submit.notRegistered.title': '您的報名尚未通過審核',
    'abstract.submit.notRegistered.desc': '投稿摘要需要先完成大會報名並通過繳費確認。請先前往報名頁面完成報名與繳費，待大會確認繳費後即可回來投稿。',
    'abstract.submit.notRegistered.btn': '前往報名專區',
    'abstract.submit.step1': '1. 論文標題 (Paper Title)',
    'abstract.submit.step2': '2. 作者群 (Authors)',
    'abstract.submit.step3': '3. 投稿分類 (Classification)',
    'abstract.submit.step4': '4. 偏好發表形式 (Presentation Preference)',
    'abstract.submit.step5': '5. 學生身份與論文獎 (Student Information)',
    'abstract.submit.step6': '6. 摘要內容 (Abstract Content)',
    'abstract.submit.title.label': '論文標題',
    'abstract.submit.title.placeholder': '請輸入論文標題（中、英文皆可）',
    'abstract.submit.authors.hint': '第一位作者預設為通訊作者，若有多位作者請依序新增。',
    'abstract.submit.author.label': '作者',
    'abstract.submit.author.corresponding': '通訊作者',
    'abstract.submit.author.name': '姓名',
    'abstract.submit.author.name.placeholder': '例：王小明 / Wang Xiao-Ming',
    'abstract.submit.author.affiliation': '所屬單位',
    'abstract.submit.author.affiliation.placeholder': '例：國立政治大學地政系',
    'abstract.submit.author.email': '電子郵件',
    'abstract.submit.author.remove': '刪除作者',
    'abstract.submit.author.add': '新增作者 (Add Author)',
    'abstract.submit.author.isCorresponding': '設為通訊作者',
    'abstract.submit.topic.label': '投稿子題 (Sub-Topic)',
    'abstract.submit.topic.placeholder': '請選擇一個最相符的子題',
    'abstract.submit.pref.oral': '口頭發表 (Oral Presentation)',
    'abstract.submit.pref.poster': '海報發表 (Poster Presentation)',
    'abstract.submit.pref.either': '口頭或海報皆可 (Either)',
    'abstract.submit.pref.hint': '實際發表形式由大會排程決定，此為偏好登記僅供參考',
    'abstract.submit.student.label': '我是學生 (I am a student)',
    'abstract.submit.student.hint': '勾選後可選擇是否報名學生論文獎',
    'abstract.submit.studentAward.label': '報名學生論文獎 (Apply for Student Paper Award)',
    'abstract.submit.studentAward.hint': '勾選表示有意願參加學生論文競賽。摘要通過審查後，大會將以 Email 通知您繳交全文。',
    'abstract.submit.abstract.label': '摘要 (Abstract)',
    'abstract.submit.abstract.placeholder': '請輸入中文或英文摘要，建議 250 字以內，包含研究目的、方法、結果與結論…',
    'abstract.submit.keywords.label': '關鍵字 (Keywords)',
    'abstract.submit.keywords.placeholder': '請以逗號分隔，至少填寫 3 個關鍵字，例如：衛星定位, GNSS, 慣性導航',
    'abstract.submit.submit': '確認並送出投稿',
    'abstract.submit.submitting': '投稿送出中...',
    'abstract.submit.save': '確認並儲存修改',
    'abstract.submit.viewSubmissions': '送出後可在「我的投稿」頁面查看投稿狀態',

    // --- Dashboard & Review Queue ---
    'dashboard.sidebar.profile': '個人資料',
    'dashboard.sidebar.myRegistrations': '我的報名',
    'dashboard.sidebar.mySubmissions': '我的投稿',
    'dashboard.sidebar.reviewQueue': '待審稿件',
    'dashboard.sidebar.notifications': '通知中心',
    'dashboard.sidebar.logout': '登出',
    'abstract.status.pending': '審核中',
    'abstract.status.accepted': '通過',
    'abstract.status.rejected': '未通過',
    'abstract.status.revision': '修改後通過',
    'abstract.type.oral': '口頭發表 (Oral)',
    'abstract.type.poster': '海報發表 (Poster)',
    'abstract.type.both': '口頭或海報皆可 (Either)',
    'abstract.session.nstc': '國科會空間資訊學門成果發表',
    'abstract.session.nlsc': '國土測繪中心成果發表會',
    'abstract.session.land': '地政司',
    'abstract.session.park': '國家公園',
    'dashboard.profile.title': '個人資料管理',
    'dashboard.profile.desc': '請確實填寫您的基本資料與聯絡方式，以便大會進行相關通知與作業。',
    'dashboard.profile.success': '個人資料更新成功！',
    'dashboard.profile.fail': '更新失敗，請稍後再試',
    'dashboard.profile.name': '真實姓名',
    'dashboard.profile.nameReq': '請輸入真實姓名',
    'dashboard.profile.email': '電子信箱 (無法修改)',
    'dashboard.profile.org': '所屬 / 服務單位',
    'dashboard.profile.orgReq': '請輸入所屬單位',
    'dashboard.profile.orgPlh': '例如：國立政治大學地政學系',
    'dashboard.profile.jobTitle': '職稱',
    'dashboard.profile.jobTitleReq': '請輸入職稱',
    'dashboard.profile.jobTitlePlh': '例如：教授、碩士生',
    'dashboard.profile.phone': '手機號碼',
    'dashboard.profile.phoneReq': '請輸入手機號碼',
    'dashboard.profile.birthday': '出生年月日',
    'dashboard.profile.birthdayReq': '請選擇出生年月日',
    'dashboard.profile.gender': '性別',
    'dashboard.profile.gender.select': '請選擇',
    'dashboard.profile.gender.male': '男',
    'dashboard.profile.gender.female': '女',
    'dashboard.profile.gender.other': '不透露 / 其他',
    'dashboard.profile.btn.saving': '儲存中...',
    'dashboard.profile.btn.save': '確認變更並儲存',
    'dashboard.reg.title': '我的報名',
    'dashboard.reg.edit': '編輯資料',
    'dashboard.reg.status.paid': '已繳費完成',
    'dashboard.reg.status.pending': '繳費審核中',
    'dashboard.reg.status.failed': '繳費異常 / 需重新上傳',
    'dashboard.reg.pending.title': '正在等待管理員對帳',
    'dashboard.reg.pending.desc1': '您的報名資料已成功送出！行政團隊將於 1~3 個工作天內核對您的匯款紀錄（帳號末五碼：',
    'dashboard.reg.pending.desc2': '）。若核對無誤，此處狀態將更新為「已繳費完成」。',
    'dashboard.reg.failed.title': '繳費對帳異常',
    'dashboard.reg.failed.desc': '很抱歉，在此紀錄中找不到符合的入帳資訊。請聯絡大會工作人員確認問題，或重新修改報名表。',
    'dashboard.reg.unlock.title': '報名繳費完成，已開放投稿功能！',
    'dashboard.reg.unlock.desc': '您的報名與繳費已被大會確認。如您有論文發表的規劃，現在可前往「我的投稿」專區上傳您的摘要。',
    'dashboard.reg.btn.goSubmissions': '前往我的投稿',
    'dashboard.reg.locked.title': '報名資料已建立，等候繳費確認中',
    'dashboard.reg.locked.desc': '您已成功建立報名資料。請注意：系統需等候大會確認您的款項無誤並將「繳費狀態」更新為「已繳費」後，您才能使用「我的投稿」專區上傳您的摘要或論文。',
    'dashboard.reg.detail.title': '報名明細',
    'dashboard.reg.detail.confName': '大會名稱',
    'dashboard.reg.detail.confValue': '第44屆測量及空間資訊研討會',
    'dashboard.reg.detail.time': '報名時間',
    'dashboard.reg.detail.ticket': '報名票種',
    'dashboard.reg.detail.amount': '應繳金額',
    'dashboard.reg.detail.last5': '匯款後五碼',
    'dashboard.reg.detail.role': '您的參與身份',
    'dashboard.reg.notReg.title': '您尚未報名本屆研討會',
    'dashboard.reg.notReg.desc': '歡迎參加第44屆測量及空間資訊研討會！點擊下方按鈕前往報名專區，了解票種資訊並完成報名手續。',
    'dashboard.reg.btn.goReg': '前往填寫報名表',
    'dashboard.reg.notice.pay.title': '匯款注意事項',
    'dashboard.reg.notice.pay.desc': '系統強制要求您於報名表單內填寫匯款對帳資訊（帳戶末五碼與日期）以利對帳。若已匯款，請直接前往報名專區進行報名。',
    'dashboard.reg.notice.sub.title': '論文審查與投稿需知',
    'dashboard.reg.notice.sub.desc1': '「我的投稿」功能需在',
    'dashboard.reg.notice.sub.desc2': '完成報名手續',
    'dashboard.reg.notice.sub.desc3': '後方得解鎖使用。如果您希望投稿摘要或論文，請先點擊上方按鈕完成表單。報名完成後，系統將自動為您開啟專區功能。',
    'dashboard.sub.notPaid.title': '您的報名尚未通過繳費審核',
    'dashboard.sub.notPaid.desc': '投稿摘要需要先完成大會報名並通過繳費確認。請先前往報名專區完成報名與繳費，待大會確認後即可開啟投稿功能。',
    'dashboard.sub.notPaid.btn': '前往報名專區',
    'dashboard.sub.empty.title': '您尚未投稿任何摘要',
    'dashboard.sub.empty.desc': '歡迎投稿第44屆測量及空間資訊研討會！點擊下方按鈕前往投稿表單。',
    'dashboard.sub.btn.goSubmit': '前往填寫投稿表單',
    'dashboard.sub.closed': '投稿已截止',
    'dashboard.sub.title': '我的投稿',
    'dashboard.sub.count': '篇',
    'dashboard.sub.btn.add': '新增投稿',
    'dashboard.sub.pub.title': '大會審查結果已發布',
    'dashboard.sub.pub.desc': '您可在下方各篇投稿中查看審查結果與評語。',
    'dashboard.sub.item.time': '投稿時間：',
    'dashboard.sub.item.btn.edit': '編輯',
    'dashboard.sub.item.label.special': '特別論壇',
    'dashboard.sub.item.label.topic': '投稿子題',
    'dashboard.sub.item.label.pref': '偏好發表形式',
    'dashboard.sub.item.label.student': '學生身份',
    'dashboard.sub.item.student.award': '學生，已報名學生論文獎',
    'dashboard.sub.item.student.normal': '學生',
    'dashboard.sub.review.title': '審查結果',
    'dashboard.sub.review.noComment': '（無評語）',
    'dashboard.sub.award.title': '學生論文獎報名',
    'dashboard.sub.award.desc': '您已報名學生論文獎競賽，大會將另行 Email 通知繳交全文的方式與截止日期，請留意信箱。',
    'dashboard.rev.title': '待審稿件',
    'dashboard.rev.count': '篇指派',
    'dashboard.rev.badge.pending': '待審',
    'dashboard.rev.badge.done': '已審',
    'dashboard.rev.empty': '目前沒有指派給您的待審稿件。',
    'dashboard.rev.detail.back': '待審清單',
    'dashboard.rev.detail.prev': '上一篇',
    'dashboard.rev.detail.next': '下一篇',
    'dashboard.rev.detail.notFound': '找不到此稿件，或您沒有審閱此文章的權限。',
    'dashboard.rev.detail.backBtn': '← 回到待審清單',
    'dashboard.rev.detail.corr': '通訊:',
    'dashboard.rev.detail.abstract': '摘要 Abstract',
    'dashboard.rev.detail.keywords': '關鍵字 Keywords',
    'dashboard.rev.detail.form.title': '審稿表單',
    'dashboard.rev.detail.form.locked': '審查結果已發布，無法再修改審查意見',
    'dashboard.rev.detail.form.decision': '審查決定',
    'dashboard.rev.detail.form.decision.pending': '尚未決定 (Pending)',
    'dashboard.rev.detail.form.decision.accept': '通過 (Accept)',
    'dashboard.rev.detail.form.decision.revision': '修改後通過 (Minor Revision)',
    'dashboard.rev.detail.form.decision.reject': '不通過 (Reject)',
    'dashboard.rev.detail.form.comments': '審閱評語 (Review Comments)',
    'dashboard.rev.detail.form.comments.plh': '在此輸入對本篇投稿的具體評語與修正建議。若選擇「修改後通過」，請說明需要修改的部分；若選擇「未通過」，請說明原因。',
    'dashboard.rev.detail.form.saving': '儲存中...',
    'dashboard.rev.detail.form.save': '儲存審查結果',
    'dashboard.rev.detail.form.saveSuccess': '審查結果已成功儲存',
    'dashboard.rev.detail.form.saveFail': '儲存失敗，請重試',
    'abstract.submit.btn.processing': '處理中...',
    'abstract.submit.btn.saveEdit': '確認並儲存修改',
    'abstract.submit.btn.submit': '確認並送出投稿',
    'abstract.submit.btn.hint': '送出後可在「我的投稿」頁面查看投稿狀態',
    // Full Paper section
    'abstract.submit.step7': '7. 全文投稿 (Full Paper，選填)',
    'abstract.submit.fullPaper.label': '全文 PDF （Full Paper PDF）',
    'abstract.submit.fullPaper.hint': '選填上傳。摘要送出後可隨時從「我的投稿」補上傳。支援格式：PDF，大小限弁20MB。',
    'abstract.submit.fullPaper.award.alert': '⚠️ 您已勾選「報名學生論文獎」，此獎項需在截止日前上傳全文才有效參賽。您可在摘要送出後從「我的投稿」補上傳。',
    'abstract.submit.fullPaper.award.deadline': '截止日：',
    'abstract.submit.fullPaper.change': '更換檔案',
    'abstract.submit.fullPaper.selected': '已選擇：',
    'abstract.submit.fullPaper.select': '選擇 PDF 檔案',
    'abstract.submit.fullPaper.uploading': '上傳中...',
    'abstract.submit.fullPaper.closed': '（全文上傳已暗法）',
    // Dashboard full paper
    'dashboard.sub.fullPaper.label': '全文投稿',
    'dashboard.sub.fullPaper.uploaded': '已上傳',
    'dashboard.sub.fullPaper.none': '尚未上傳全文（選填）',
    'dashboard.sub.fullPaper.awardAlert': '上傳全文才能參加學生論文獎！',
    'dashboard.sub.fullPaper.upload': '上傳全文',
    'dashboard.sub.fullPaper.replace': '更換全文',
    'dashboard.sub.fullPaper.view': '檢視全文',
    'dashboard.sub.fullPaper.uploading': '上傳中...',
    'dashboard.sub.fullPaper.uploadFail': '上傳失敗，請重試',
    'dashboard.notif.empty': '尚無新通知。',
    'dashboard.notif.regPaid.title': '報名繳費成功',
    'dashboard.notif.regPaid.desc': '您的研討會報名與繳費已被大會確認，現在您可以自由使用「我的投稿」功能。',
    'dashboard.notif.regFailed.title': '繳費對帳異常',
    'dashboard.notif.regFailed.desc': '我們無法核實您的繳費資訊，請前往「我的報名」查閱詳細資訊或聯絡大會。',
    'dashboard.notif.absAccept.title': '摘要審查通過',
    'dashboard.notif.absAccept.desc': '您的摘要「{title}」已通過大會審查！',
    'dashboard.notif.absRevision.title': '摘要需修改後通過',
    'dashboard.notif.absRevision.desc': '您的摘要「{title}」獲評為修改後通過，請依評語進行修正。',
    'dashboard.notif.absReject.title': '摘要未通過',
    'dashboard.notif.absReject.desc': '您的摘要「{title}」未通過本次審查，感謝您的投稿。',
    'dashboard.notif.btn.view': '查看詳情'
  },
  en: {
    // Navbar sections
    'nav.home': 'Home',
    'nav.news': 'News',
    'nav.registration': 'Registration',
    'nav.registration.timeline': 'Schedule',
    'nav.registration.fees': 'Fees',
    'nav.registration.method': 'How to Register',
    'nav.registration.notice': 'Notice',
    'nav.registration.go': 'Register Now',
    'nav.submission': 'Submission',
    'nav.submission.guide': 'Submission Guide',
    'nav.submission.guidelines': 'Presentation Guidelines',
    'nav.submission.go': 'Submit Now',
    'nav.sponsors': 'Sponsors',
    'nav.sponsors.units': 'Exhibitors & Sponsors',
    'nav.about': 'Info',
    'nav.about.intro': 'About',
    'nav.about.transport': 'Transportation',
    'nav.about.contact': 'Contact Us',
    'nav.3s': '3S Maker',
    'nav.3s.rules': 'Competition Rules',
    // User area
    'auth.login': '     Login     ',
    'auth.loginRegister': 'Login / Register',
    'auth.member': 'My Account',
    'auth.loggedInAs': 'Logged in as',
    'auth.logout': 'Sign Out',
    'auth.loginError': 'The email or password provided is incorrect.',
    // Login page
    'login.title': 'Login to SG44',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot Password?',
    'login.submit': 'Login',
    'login.submitting': 'Logging in...',
    'login.noAccount': "Don't have an account?",
    'login.registerNow': 'Register Now',
    'login.error.default': 'Login failed, please check your credentials',
    'login.error.credentials': 'Login failed, please make sure your email and password are correct.',
    // Register page
    'register.title': 'Create Member Account',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.password.hint': 'At least 6 characters',
    'register.confirmPassword': 'Confirm Password',
    'register.organization': 'Organization',
    'register.organization.hint': 'University or Company',
    'register.jobTitle': 'Job Title',
    'register.jobTitle.hint': 'e.g., Professor, Student',
    'register.phone': 'Phone Number',
    'register.birthday': 'Date of Birth',
    'register.gender': 'Gender (Optional)',
    'register.gender.placeholder': 'Select...',
    'register.gender.male': 'Male',
    'register.gender.female': 'Female',
    'register.gender.other': 'Other',
    'register.details': 'Detailed Information',
    'register.submit': 'Register account',
    'register.submitting': 'Registering...',
    'register.haveAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.success.title': 'Registration Successful!',
    'register.success.msg': 'A verification email has been sent. Please check your inbox and click the link to activate your account.',
    'register.error.exists': 'This email has already been registered. Please login or use forgot password.',
    'register.error.validation': 'Invalid data format, please check your input.',
    // General Validation
    'validation.required': 'This field is required',
    'validation.email': 'Please enter a valid email address',
    'validation.passwordMatch': 'Passwords do not match',
    // SG44 Register form
    'sg44.title': 'Registration System',
    'sg44.subtitle': 'Conference Registration',
    'sg44.desc': 'Welcome to register for the 44th Surveying and Geoinformatics Conference. The conference will be held at National Chengchi University from 2026.08.20 ~ 2026.08.21.',
    'sg44.payment.info': 'Payment Info',
    'sg44.payment.method': 'Payment Method',
    'sg44.payment.bank': 'Bank Transfer (E.SUN Bank 808)',
    'sg44.step1': '1. Ticketing',
    'sg44.step2': '2. Personal Info',
    'sg44.step3': '3. Participation',
    'sg44.step4': '4. Payment Verification',
    'sg44.step5': '5. Meals & Events',
    'sg44.submit': 'Submit Registration',
    'sg44.submit.submitting': 'Processing...',
    // Abstract Submit
    'abstract.submit.title': 'Abstract Submission System',
    'abstract.submit.subtitle': 'Abstract Submission',
    'abstract.submit.desc': 'Welcome to the 44th Surveying and Geoinformatics Conference abstract submission. Please fill in author info, category, and abstract content in order.',
    'abstract.submit.closed.title': 'Abstract Submission Closed',
    'abstract.submit.closed.desc': 'The submission system is currently closed. Thank you for your interest.',
    'abstract.submit.notRegistered.title': 'Registration Not Verified',
    'abstract.submit.notRegistered.desc': 'Abstract submission requires conference registration and payment verification. Please register and pay first, then return to submit your abstract after verification.',
    'abstract.submit.notRegistered.btn': 'Go to Registration',
    'abstract.submit.step1': '1. Paper Title',
    'abstract.submit.step2': '2. Authors',
    'abstract.submit.step3': '3. Classification',
    'abstract.submit.step4': '4. Presentation Preference',
    'abstract.submit.step5': '5. Student Information',
    'abstract.submit.step6': '6. Abstract Content',
    'abstract.submit.title.label': 'Paper Title',
    'abstract.submit.title.placeholder': 'Enter paper title (Chinese or English)',
    'abstract.submit.authors.hint': 'The first author is the corresponding author by default. Add others in order.',
    'abstract.submit.author.label': 'Author',
    'abstract.submit.author.corresponding': 'Corresponding Author',
    'abstract.submit.author.name': 'Name',
    'abstract.submit.author.name.placeholder': 'e.g., Wang Xiao-Ming',
    'abstract.submit.author.affiliation': 'Affiliation',
    'abstract.submit.author.affiliation.placeholder': 'e.g., Dept. of Land Economics, NCCU',
    'abstract.submit.author.email': 'Email',
    'abstract.submit.author.remove': 'Remove Author',
    'abstract.submit.author.add': 'Add Author',
    'abstract.submit.author.isCorresponding': 'Set as Corresponding Author',
    'abstract.submit.topic.label': 'Sub-Topic',
    'abstract.submit.topic.placeholder': 'Select the most relevant sub-topic',
    'abstract.submit.pref.oral': 'Oral Presentation',
    'abstract.submit.pref.poster': 'Poster Presentation',
    'abstract.submit.pref.either': 'Either',
    'abstract.submit.pref.hint': 'Final presentation format is decided by the committee; this preference is for reference only.',
    'abstract.submit.student.label': 'I am a student',
    'abstract.submit.student.hint': 'Check this to apply for the Student Paper Award',
    'abstract.submit.studentAward.label': 'Apply for Student Paper Award',
    'abstract.submit.studentAward.hint': 'Checking this indicates interest in the Student Paper Competition. You will be notified to submit the full paper after the abstract is accepted.',
    'abstract.submit.abstract.label': 'Abstract',
    'abstract.submit.abstract.placeholder': 'Enter abstract (ZH/EN), suggested under 250 words, including purpose, methods, results, and conclusions...',
    'abstract.submit.keywords.label': 'Keywords',
    'abstract.submit.keywords.placeholder': 'Comma-separated, at least 3 keywords, e.g., GNSS, GIS, Remote Sensing',
    'abstract.submit.submit': 'Confirm and Submit',
    'abstract.submit.submitting': 'Submitting...',
    'abstract.submit.save': 'Confirm and Save Changes',
    'abstract.submit.viewSubmissions': 'You can view submission status in "My Submissions" after sending.',

    // --- Dashboard & Review Queue ---
    'dashboard.sidebar.profile': 'Profile',
    'dashboard.sidebar.myRegistrations': 'My Registrations',
    'dashboard.sidebar.mySubmissions': 'My Submissions',
    'dashboard.sidebar.reviewQueue': 'Review Queue',
    'dashboard.sidebar.notifications': 'Notifications',
    'dashboard.sidebar.logout': 'Log Out',
    'abstract.status.pending': 'Under Review',
    'abstract.status.accepted': 'Accepted',
    'abstract.status.rejected': 'Rejected',
    'abstract.status.revision': 'Accepted with Minor Revision',
    'abstract.type.oral': 'Oral Presentation',
    'abstract.type.poster': 'Poster Presentation',
    'abstract.type.both': 'Oral or Poster',
    'abstract.session.nstc': 'NSTC Spatial Information Results',
    'abstract.session.nlsc': 'NLSC Results Presentation',
    'abstract.session.land': 'Department of Land Administration',
    'abstract.session.park': 'National Parks',
    'dashboard.profile.title': 'Profile Management',
    'dashboard.profile.desc': 'Please fill in your basic information and contact details accurately for conference notifications.',
    'dashboard.profile.success': 'Profile updated successfully!',
    'dashboard.profile.fail': 'Update failed, please try again.',
    'dashboard.profile.name': 'Full Name',
    'dashboard.profile.nameReq': 'Please enter your full name',
    'dashboard.profile.email': 'Email (Cannot be changed)',
    'dashboard.profile.org': 'Organization / Institution',
    'dashboard.profile.orgReq': 'Please enter your organization',
    'dashboard.profile.orgPlh': 'e.g., Dept. of Land Economics, NCCU',
    'dashboard.profile.jobTitle': 'Job Title',
    'dashboard.profile.jobTitleReq': 'Please enter your job title',
    'dashboard.profile.jobTitlePlh': 'e.g., Professor, Master Student',
    'dashboard.profile.phone': 'Mobile Phone',
    'dashboard.profile.phoneReq': 'Please enter your mobile phone',
    'dashboard.profile.birthday': 'Date of Birth',
    'dashboard.profile.birthdayReq': 'Please select your date of birth',
    'dashboard.profile.gender': 'Gender',
    'dashboard.profile.gender.select': 'Please select',
    'dashboard.profile.gender.male': 'Male',
    'dashboard.profile.gender.female': 'Female',
    'dashboard.profile.gender.other': 'Prefer not to say / Other',
    'dashboard.profile.btn.saving': 'Saving...',
    'dashboard.profile.btn.save': 'Save Changes',
    'dashboard.reg.title': 'My Registrations',
    'dashboard.reg.edit': 'Edit Data',
    'dashboard.reg.status.paid': 'Payment Completed',
    'dashboard.reg.status.pending': 'Payment Under Review',
    'dashboard.reg.status.failed': 'Payment Failed / Re-upload Required',
    'dashboard.reg.pending.title': 'Waiting for Admin Verification',
    'dashboard.reg.pending.desc1': 'Your registration data has been submitted! The administrative team will verify your payment record within 1-3 working days (Last 5 digits: ',
    'dashboard.reg.pending.desc2': '). If verified, the status here will be updated to "Payment Completed".',
    'dashboard.reg.failed.title': 'Payment Verification Error',
    'dashboard.reg.failed.desc': 'Sorry, we could not find matching payment information in the records. Please contact conference staff or modify your registration.',
    'dashboard.reg.unlock.title': 'Registration and Payment Completed. Abstract submission is now open!',
    'dashboard.reg.unlock.desc': 'Your registration and payment have been confirmed. To present a paper, please proceed to the "My Submissions" area to upload your abstract.',
    'dashboard.reg.btn.goSubmissions': 'Go to My Submissions',
    'dashboard.reg.locked.title': 'Registration Created, Awaiting Payment Confirmation',
    'dashboard.reg.locked.desc': 'You have successfully created your registration data. Please note: You must wait for the conference to confirm your payment and update the "Payment Status" to "Paid" before you can use the "My Submissions" area.',
    'dashboard.reg.detail.title': 'Registration Details',
    'dashboard.reg.detail.confName': 'Conference Name',
    'dashboard.reg.detail.confValue': 'The 44th Surveying and Spatial Information Conference',
    'dashboard.reg.detail.time': 'Registration Time',
    'dashboard.reg.detail.ticket': 'Ticket Type',
    'dashboard.reg.detail.amount': 'Amount Payable',
    'dashboard.reg.detail.last5': 'Last 5 Digits',
    'dashboard.reg.detail.role': 'Participant Role',
    'dashboard.reg.notReg.title': 'You have not registered for this conference yet',
    'dashboard.reg.notReg.desc': 'Welcome to the 44th Surveying and Spatial Information Conference! Click the button below to proceed to the registration area, learn about ticket options, and complete registration.',
    'dashboard.reg.btn.goReg': 'Go to Registration Form',
    'dashboard.reg.notice.pay.title': 'Payment Notice',
    'dashboard.reg.notice.pay.desc': 'The system requires you to fill in your payment verification information in the registration form for accounting purposes. If you have already transferred the payment, please proceed directly to the registration area to enroll.',
    'dashboard.reg.notice.sub.title': 'Abstract Review and Submission Notice',
    'dashboard.reg.notice.sub.desc1': 'The "My Submissions" function will be unlocked after ',
    'dashboard.reg.notice.sub.desc2': 'completing registration',
    'dashboard.reg.notice.sub.desc3': '. If you wish to submit an abstract or paper, please click the button above to complete the form first. After registration, the system will automatically enable the submission area for you.',
    'dashboard.sub.notPaid.title': 'Your registration payment is not yet verified',
    'dashboard.sub.notPaid.desc': 'Abstract submission requires completing conference registration and passing payment verification first. Please proceed to the registration area to complete payment. Once confirmed, submission will be enabled.',
    'dashboard.sub.notPaid.btn': 'Go to Registration Area',
    'dashboard.sub.empty.title': 'You have not submitted any abstracts',
    'dashboard.sub.empty.desc': 'Welcome to submit to the 44th Surveying and Spatial Information Conference! Click the button below to go to the submission form.',
    'dashboard.sub.btn.goSubmit': 'Go to Submission Form',
    'dashboard.sub.closed': 'Submission Closed',
    'dashboard.sub.title': 'My Submissions',
    'dashboard.sub.count': 'papers',
    'dashboard.sub.btn.add': 'Add Submission',
    'dashboard.sub.pub.title': 'Conference Review Results Published',
    'dashboard.sub.pub.desc': 'You can check the review results and comments in your submissions below.',
    'dashboard.sub.item.time': 'Submitted at: ',
    'dashboard.sub.item.btn.edit': 'Edit',
    'dashboard.sub.item.label.special': 'Special Session',
    'dashboard.sub.item.label.topic': 'Sub-topic',
    'dashboard.sub.item.label.pref': 'Presentation Preference',
    'dashboard.sub.item.label.student': 'Student Status',
    'dashboard.sub.item.student.award': 'Student, applied for Best Student Paper Award',
    'dashboard.sub.item.student.normal': 'Student',
    'dashboard.sub.review.title': 'Review Result',
    'dashboard.sub.review.noComment': '(No comments)',
    'dashboard.sub.award.title': 'Best Student Paper Award Registration',
    'dashboard.sub.award.desc': 'You have registered for the Best Student Paper Award. The conference will send another Email regarding the full paper submission method and deadline. Please check your inbox.',
    'dashboard.rev.title': 'Review Queue',
    'dashboard.rev.count': 'assigned',
    'dashboard.rev.badge.pending': 'Pending',
    'dashboard.rev.badge.done': 'Reviewed',
    'dashboard.rev.empty': 'You currently have no abstracts assigned for review.',
    'dashboard.rev.detail.back': 'Review Queue List',
    'dashboard.rev.detail.prev': 'Previous',
    'dashboard.rev.detail.next': 'Next',
    'dashboard.rev.detail.notFound': 'Abstract not found, or you do not have permission to review it.',
    'dashboard.rev.detail.backBtn': '← Back to List',
    'dashboard.rev.detail.corr': 'Corresponding:',
    'dashboard.rev.detail.abstract': 'Abstract',
    'dashboard.rev.detail.keywords': 'Keywords',
    'dashboard.rev.detail.form.title': 'Review Form',
    'dashboard.rev.detail.form.locked': 'Review results are published; comments can no longer be modified.',
    'dashboard.rev.detail.form.decision': 'Review Decision',
    'dashboard.rev.detail.form.decision.pending': 'Pending Decision',
    'dashboard.rev.detail.form.decision.accept': 'Accept',
    'dashboard.rev.detail.form.decision.revision': 'Minor Revision',
    'dashboard.rev.detail.form.decision.reject': 'Reject',
    'dashboard.rev.detail.form.comments': 'Review Comments',
    'dashboard.rev.detail.form.comments.plh': 'Enter detailed comments and revision suggestions here. If selecting "Minor Revision", please explain what needs modifying; if "Reject", please explain the reason.',
    'dashboard.rev.detail.form.saving': 'Saving...',
    'dashboard.rev.detail.form.save': 'Save Review Decision',
    'dashboard.rev.detail.form.saveSuccess': 'Review decision saved successfully',
    'dashboard.rev.detail.form.saveFail': 'Failed to save, please try again',
    'abstract.submit.btn.processing': 'Processing...',
    'abstract.submit.btn.saveEdit': 'Confirm & Save Changes',
    'abstract.submit.btn.submit': 'Confirm and Submit',
    'abstract.submit.btn.hint': 'You can view submission status in "My Submissions" after sending.',
    // Full Paper section
    'abstract.submit.step7': '7. Full Paper (Optional)',
    'abstract.submit.fullPaper.label': 'Full Paper PDF',
    'abstract.submit.fullPaper.hint': 'Optional upload. You can also submit the full paper anytime from "My Submissions". PDF only, max 20MB.',
    'abstract.submit.fullPaper.award.alert': '⚠️ You have selected the Student Paper Award. A full paper is required before the deadline to be eligible. You can upload it anytime from "My Submissions".',
    'abstract.submit.fullPaper.award.deadline': 'Deadline: ',
    'abstract.submit.fullPaper.change': 'Change File',
    'abstract.submit.fullPaper.selected': 'Selected: ',
    'abstract.submit.fullPaper.select': 'Select PDF File',
    'abstract.submit.fullPaper.uploading': 'Uploading...',
    'abstract.submit.fullPaper.closed': '(Full paper upload is closed)',
    // Dashboard full paper
    'dashboard.sub.fullPaper.label': 'Full Paper',
    'dashboard.sub.fullPaper.uploaded': 'Uploaded',
    'dashboard.sub.fullPaper.none': 'Not uploaded (optional)',
    'dashboard.sub.fullPaper.awardAlert': 'A full paper is required to compete for the Student Paper Award!',
    'dashboard.sub.fullPaper.upload': 'Upload Full Paper',
    'dashboard.sub.fullPaper.replace': 'Replace Full Paper',
    'dashboard.sub.fullPaper.view': 'View Full Paper',
    'dashboard.sub.fullPaper.uploading': 'Uploading...',
    'dashboard.sub.fullPaper.uploadFail': 'Upload failed, please retry',
    'dashboard.notif.empty': 'No new notifications.',
    'dashboard.notif.regPaid.title': 'Payment Verified',
    'dashboard.notif.regPaid.desc': 'Your conference registration and payment have been confirmed. Abstract submission is now unlocked.',
    'dashboard.notif.regFailed.title': 'Payment Verification Failed',
    'dashboard.notif.regFailed.desc': 'We could not verify your payment. Please check "My Registrations" for details or contact us.',
    'dashboard.notif.absAccept.title': 'Abstract Accepted',
    'dashboard.notif.absAccept.desc': 'Your abstract "{title}" has been accepted!',
    'dashboard.notif.absRevision.title': 'Abstract Accepted with Minor Revision',
    'dashboard.notif.absRevision.desc': 'Your abstract "{title}" has been accepted with minor revisions required.',
    'dashboard.notif.absReject.title': 'Abstract Rejected',
    'dashboard.notif.absReject.desc': 'Your abstract "{title}" was not accepted. Thank you for your submission.',
    'dashboard.notif.btn.view': 'View Details'
  },
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'zh',
  setLang: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('zh')

  const t = (key: string): string => {
    return translations[lang][key] ?? translations['zh'][key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextType {
  return useContext(LanguageContext)
}
