'use client'

import React, { createContext, useContext, useState } from 'react'

type Language = 'zh' | 'en'

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar sections
    'nav.home': '首頁',
    'nav.news': '最新消息',
    'nav.registration': '會議報名',
    'nav.registration.timeline': '報名時程',
    'nav.registration.fees': '報名費用',
    'nav.registration.method': '報名方式',
    'nav.registration.notice': '報名須知',
    'nav.registration.go': '前往報名',
    'nav.submission': '論文發表',
    'nav.submission.guide': '投稿說明',
    'nav.submission.guidelines': '發表注意事項',
    'nav.submission.go': '前往投稿',
    'nav.sponsors': '參展贊助',
    'nav.sponsors.units': '參展及贊助單位',
    'nav.about': '會議資訊',
    'nav.about.intro': '會議介紹',
    'nav.about.transport': '交通資訊',
    'nav.about.contact': '聯絡我們',
    'nav.3s': '3S創客競賽',
    'nav.3s.rules': '競賽細則',
    // User area
    'auth.login': '會員登入',
    'auth.loginRegister': '會員登入 / 註冊',
    'auth.member': '會員中心',
    'auth.loggedInAs': '已登入為',
    'auth.logout': '登出',
    'auth.loginError': '帳號或密碼輸入錯誤，請再試一次。',
    // Login page
    'login.title': '登入 SG44',
    'login.email': 'Email',
    'login.password': '密碼',
    'login.forgotPassword': '忘記密碼？',
    'login.submit': '登入',
    'login.submitting': '登入中...',
    'login.noAccount': '還沒有帳號？',
    'login.registerNow': '立即註冊',
    'login.error.default': '登入失敗，請檢查帳號密碼',
    'login.error.credentials': '登入失敗，請確認您的信箱與密碼是否完全正確。',
    // Register page
    'register.title': '註冊會員帳號',
    'register.name': '姓名',
    'register.email': 'Email',
    'register.password': '密碼',
    'register.password.hint': '密碼至少需 6 碼',
    'register.confirmPassword': '確認密碼',
    'register.organization': '所屬單位',
    'register.organization.hint': '學校或公司',
    'register.jobTitle': '職稱',
    'register.jobTitle.hint': '如: 教授、學生',
    'register.phone': '手機號碼',
    'register.birthday': '出生年月日',
    'register.gender': '性別 (選填)',
    'register.gender.placeholder': '請選擇',
    'register.gender.male': '男',
    'register.gender.female': '女',
    'register.gender.other': '不透露/其他',
    'register.details': '詳細資料',
    'register.submit': '註冊帳號',
    'register.submitting': '註冊中...',
    'register.haveAccount': '已經有帳號了嗎？',
    'register.login': '登入',
    'register.success.title': '註冊成功！',
    'register.success.msg': '驗證信件已發送至您的信箱，請查收並點擊連結啟用帳號。',
    'register.error.exists': '這個信箱已經被註冊過了，請直接登入或使用忘記密碼。',
    'register.error.validation': '部分資料格式不符，請檢查輸入內容是否完整。',
    // General Validation
    'validation.required': '此欄位為必填',
    'validation.email': '請輸入正確的 Email 格式',
    'validation.passwordMatch': '兩次密碼不一致',
    // SG44 Register form
    'sg44.title': '研討會報名系統',
    'sg44.subtitle': 'Conference Registration',
    'sg44.desc': '歡迎報名【第44屆測量及空間資訊研討會】。大會將於 2026.08.20 ~ 2026.08.21 假國立政治大學舉辦。',
    'sg44.payment.info': '繳費資訊',
    'sg44.payment.method': '繳費方式',
    'sg44.payment.bank': '銀行轉帳 (808 玉山銀行)',
    'sg44.step1': '1. 報名費與票種選擇',
    'sg44.step2': '2. 基本資料',
    'sg44.step3': '3. 會議參與資訊',
    'sg44.step4': '4. 繳費對帳資訊',
    'sg44.step5': '5. 膳食與活動意願',
    'sg44.submit': '確認資料無誤並送出報名表',
    'sg44.submit.submitting': '報名資料處理中...',
    // Abstract Submit
    'abstract.submit.title': '摘要投稿系統',
    'abstract.submit.subtitle': 'Abstract Submission',
    'abstract.submit.desc': '歡迎投稿第44屆測量及空間資訊研討會。請依序填寫作者資訊、投稿分類與摘要內容。',
    'abstract.submit.closed.title': '摘要投稿已截止',
    'abstract.submit.closed.desc': '目前投稿系統已關閉，感謝您的參與。',
    'abstract.submit.notRegistered.title': '您的報名尚未通過審核',
    'abstract.submit.notRegistered.desc': '投稿摘要需要先完成大會報名並通過繳費確認。請先前往報名頁面完成報名與繳費，待大會確認繳費後即可回來投稿。',
    'abstract.submit.notRegistered.btn': '前往報名專區',
    'abstract.submit.step1': '1. 論文標題 (Paper Title)',
    'abstract.submit.step2': '2. 作者群 (Authors)',
    'abstract.submit.step3': '3. 投稿分類 (Classification)',
    'abstract.submit.step4': '4. 偏好發表形式 (Presentation Preference)',
    'abstract.submit.step5': '5. 學生身份與論文獎 (Student Information)',
    'abstract.submit.step6': '6. 摘要內容 (Abstract Content)',
    'abstract.submit.title.label': '論文標題',
    'abstract.submit.title.placeholder': '請輸入論文標題（中、英文皆可）',
    'abstract.submit.authors.hint': '第一位作者預設為通訊作者，若有多位作者請依序新增。',
    'abstract.submit.author.label': '作者',
    'abstract.submit.author.corresponding': '通訊作者',
    'abstract.submit.author.name': '姓名',
    'abstract.submit.author.name.placeholder': '例：王小明 / Wang Xiao-Ming',
    'abstract.submit.author.affiliation': '所屬單位',
    'abstract.submit.author.affiliation.placeholder': '例：國立政治大學地政系',
    'abstract.submit.author.email': '電子郵件',
    'abstract.submit.author.remove': '刪除作者',
    'abstract.submit.author.add': '新增作者 (Add Author)',
    'abstract.submit.author.isCorresponding': '設為通訊作者',
    'abstract.submit.topic.label': '投稿子題 (Sub-Topic)',
    'abstract.submit.topic.placeholder': '請選擇一個最相符的子題',
    'abstract.submit.pref.oral': '口頭發表 (Oral Presentation)',
    'abstract.submit.pref.poster': '海報發表 (Poster Presentation)',
    'abstract.submit.pref.either': '口頭或海報皆可 (Either)',
    'abstract.submit.pref.hint': '實際發表形式由大會排程決定，此為偏好登記僅供參考',
    'abstract.submit.student.label': '我是學生 (I am a student)',
    'abstract.submit.student.hint': '勾選後可選擇是否報名學生論文獎',
    'abstract.submit.studentAward.label': '報名學生論文獎 (Apply for Student Paper Award)',
    'abstract.submit.studentAward.hint': '勾選表示有意願參加學生論文競賽。摘要通過審查後，大會將以 Email 通知您繳交全文。',
    'abstract.submit.abstract.label': '摘要 (Abstract)',
    'abstract.submit.abstract.placeholder': '請輸入中文或英文摘要，建議 250 字以內，包含研究目的、方法、結果與結論…',
    'abstract.submit.keywords.label': '關鍵字 (Keywords)',
    'abstract.submit.keywords.placeholder': '請以逗號分隔，至少填寫 3 個關鍵字，例如：衛星定位, GNSS, 慣性導航',
    'abstract.submit.submit': '確認並送出投稿',
    'abstract.submit.submitting': '投稿送出中...',
    'abstract.submit.save': '確認並儲存修改',
    'abstract.submit.viewSubmissions': '送出後可在「我的投稿」頁面查看投稿狀態',
  },
  en: {
    // Navbar sections
    'nav.home': 'Home',
    'nav.news': 'News',
    'nav.registration': 'Registration',
    'nav.registration.timeline': 'Schedule',
    'nav.registration.fees': 'Fees',
    'nav.registration.method': 'How to Register',
    'nav.registration.notice': 'Notice',
    'nav.registration.go': 'Register Now',
    'nav.submission': 'Submission',
    'nav.submission.guide': 'Submission Guide',
    'nav.submission.guidelines': 'Presentation Guidelines',
    'nav.submission.go': 'Submit Now',
    'nav.sponsors': 'Sponsors',
    'nav.sponsors.units': 'Exhibitors & Sponsors',
    'nav.about': 'Info',
    'nav.about.intro': 'About',
    'nav.about.transport': 'Transportation',
    'nav.about.contact': 'Contact Us',
    'nav.3s': '3S Maker',
    'nav.3s.rules': 'Competition Rules',
    // User area
    'auth.login': '     Login     ',
    'auth.loginRegister': 'Login / Register',
    'auth.member': 'My Account',
    'auth.loggedInAs': 'Logged in as',
    'auth.logout': 'Sign Out',
    'auth.loginError': 'The email or password provided is incorrect.',
    // Login page
    'login.title': 'Login to SG44',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot Password?',
    'login.submit': 'Login',
    'login.submitting': 'Logging in...',
    'login.noAccount': "Don't have an account?",
    'login.registerNow': 'Register Now',
    'login.error.default': 'Login failed, please check your credentials',
    'login.error.credentials': 'Login failed, please make sure your email and password are correct.',
    // Register page
    'register.title': 'Create Member Account',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.password.hint': 'At least 6 characters',
    'register.confirmPassword': 'Confirm Password',
    'register.organization': 'Organization',
    'register.organization.hint': 'University or Company',
    'register.jobTitle': 'Job Title',
    'register.jobTitle.hint': 'e.g., Professor, Student',
    'register.phone': 'Phone Number',
    'register.birthday': 'Date of Birth',
    'register.gender': 'Gender (Optional)',
    'register.gender.placeholder': 'Select...',
    'register.gender.male': 'Male',
    'register.gender.female': 'Female',
    'register.gender.other': 'Other',
    'register.details': 'Detailed Information',
    'register.submit': 'Register account',
    'register.submitting': 'Registering...',
    'register.haveAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.success.title': 'Registration Successful!',
    'register.success.msg': 'A verification email has been sent. Please check your inbox and click the link to activate your account.',
    'register.error.exists': 'This email has already been registered. Please login or use forgot password.',
    'register.error.validation': 'Invalid data format, please check your input.',
    // General Validation
    'validation.required': 'This field is required',
    'validation.email': 'Please enter a valid email address',
    'validation.passwordMatch': 'Passwords do not match',
    // SG44 Register form
    'sg44.title': 'Registration System',
    'sg44.subtitle': 'Conference Registration',
    'sg44.desc': 'Welcome to register for the 44th Surveying and Geoinformatics Conference. The conference will be held at National Chengchi University from 2026.08.20 ~ 2026.08.21.',
    'sg44.payment.info': 'Payment Info',
    'sg44.payment.method': 'Payment Method',
    'sg44.payment.bank': 'Bank Transfer (E.SUN Bank 808)',
    'sg44.step1': '1. Ticketing',
    'sg44.step2': '2. Personal Info',
    'sg44.step3': '3. Participation',
    'sg44.step4': '4. Payment Verification',
    'sg44.step5': '5. Meals & Events',
    'sg44.submit': 'Submit Registration',
    'sg44.submit.submitting': 'Processing...',
    // Abstract Submit
    'abstract.submit.title': 'Abstract Submission System',
    'abstract.submit.subtitle': 'Abstract Submission',
    'abstract.submit.desc': 'Welcome to the 44th Surveying and Geoinformatics Conference abstract submission. Please fill in author info, category, and abstract content in order.',
    'abstract.submit.closed.title': 'Abstract Submission Closed',
    'abstract.submit.closed.desc': 'The submission system is currently closed. Thank you for your interest.',
    'abstract.submit.notRegistered.title': 'Registration Not Verified',
    'abstract.submit.notRegistered.desc': 'Abstract submission requires conference registration and payment verification. Please register and pay first, then return to submit your abstract after verification.',
    'abstract.submit.notRegistered.btn': 'Go to Registration',
    'abstract.submit.step1': '1. Paper Title',
    'abstract.submit.step2': '2. Authors',
    'abstract.submit.step3': '3. Classification',
    'abstract.submit.step4': '4. Presentation Preference',
    'abstract.submit.step5': '5. Student Information',
    'abstract.submit.step6': '6. Abstract Content',
    'abstract.submit.title.label': 'Paper Title',
    'abstract.submit.title.placeholder': 'Enter paper title (Chinese or English)',
    'abstract.submit.authors.hint': 'The first author is the corresponding author by default. Add others in order.',
    'abstract.submit.author.label': 'Author',
    'abstract.submit.author.corresponding': 'Corresponding Author',
    'abstract.submit.author.name': 'Name',
    'abstract.submit.author.name.placeholder': 'e.g., Wang Xiao-Ming',
    'abstract.submit.author.affiliation': 'Affiliation',
    'abstract.submit.author.affiliation.placeholder': 'e.g., Dept. of Land Economics, NCCU',
    'abstract.submit.author.email': 'Email',
    'abstract.submit.author.remove': 'Remove Author',
    'abstract.submit.author.add': 'Add Author',
    'abstract.submit.author.isCorresponding': 'Set as Corresponding Author',
    'abstract.submit.topic.label': 'Sub-Topic',
    'abstract.submit.topic.placeholder': 'Select the most relevant sub-topic',
    'abstract.submit.pref.oral': 'Oral Presentation',
    'abstract.submit.pref.poster': 'Poster Presentation',
    'abstract.submit.pref.either': 'Either',
    'abstract.submit.pref.hint': 'Final presentation format is decided by the committee; this preference is for reference only.',
    'abstract.submit.student.label': 'I am a student',
    'abstract.submit.student.hint': 'Check this to apply for the Student Paper Award',
    'abstract.submit.studentAward.label': 'Apply for Student Paper Award',
    'abstract.submit.studentAward.hint': 'Checking this indicates interest in the Student Paper Competition. You will be notified to submit the full paper after the abstract is accepted.',
    'abstract.submit.abstract.label': 'Abstract',
    'abstract.submit.abstract.placeholder': 'Enter abstract (ZH/EN), suggested under 250 words, including purpose, methods, results, and conclusions...',
    'abstract.submit.keywords.label': 'Keywords',
    'abstract.submit.keywords.placeholder': 'Comma-separated, at least 3 keywords, e.g., GNSS, GIS, Remote Sensing',
    'abstract.submit.submit': 'Confirm and Submit',
    'abstract.submit.submitting': 'Submitting...',
    'abstract.submit.save': 'Confirm and Save Changes',
    'abstract.submit.viewSubmissions': 'You can view submission status in "My Submissions" after sending.',
  },
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'zh',
  setLang: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('zh')

  const t = (key: string): string => {
    return translations[lang][key] ?? translations['zh'][key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextType {
  return useContext(LanguageContext)
}
