/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_gender = pgEnum('enum_users_gender', ['male', 'female', 'other'])
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'user', 'reviewer'])
export const enum_news_related_files_type = pgEnum('enum_news_related_files_type', ['file', 'link'])
export const enum_news_category = pgEnum('enum_news_category', [
  '重要公告',
  '徵稿資訊',
  '會議議程',
  '註冊報名',
  '榮譽榜單',
  '一般消息',
])
export const enum_news_status = pgEnum('enum_news_status', ['draft', 'published'])
export const enum__news_v_version_related_files_type = pgEnum(
  'enum__news_v_version_related_files_type',
  ['file', 'link'],
)
export const enum__news_v_version_category = pgEnum('enum__news_v_version_category', [
  '重要公告',
  '徵稿資訊',
  '會議議程',
  '註冊報名',
  '榮譽榜單',
  '一般消息',
])
export const enum__news_v_version_status = pgEnum('enum__news_v_version_status', [
  'draft',
  'published',
])
export const enum_registrations_ticket_type = pgEnum('enum_registrations_ticket_type', [
  'early-bird-student',
  'early-bird-regular',
  'standard-student',
  'standard-regular',
])
export const enum_registrations_payment_status = pgEnum('enum_registrations_payment_status', [
  'pending',
  'paid',
  'failed',
])
export const enum_registrations_participant_role = pgEnum('enum_registrations_participant_role', [
  'presenter',
  'keynote',
  'host',
  'discussant',
  'attendee',
  'staff',
  'vip',
  'other',
])
export const enum_registrations_presentation_type = pgEnum('enum_registrations_presentation_type', [
  'oral',
  'poster',
  'both',
  'none',
])
export const enum_registrations_meal_day1 = pgEnum('enum_registrations_meal_day1', ['yes', 'no'])
export const enum_registrations_meal_day2 = pgEnum('enum_registrations_meal_day2', ['yes', 'no'])
export const enum_registrations_banquet = pgEnum('enum_registrations_banquet', ['yes', 'no'])
export const enum_registrations_dietary_preference = pgEnum(
  'enum_registrations_dietary_preference',
  ['regular', 'vegetarian', 'other'],
)
export const enum_abstracts_sub_topic = pgEnum('enum_abstracts_sub_topic', [
  'topic-1',
  'topic-2',
  'topic-3',
  'topic-4',
  'topic-5',
  'topic-6',
  'topic-7',
  'topic-8',
  'topic-9',
  'topic-10',
])
export const enum_abstracts_special_session = pgEnum('enum_abstracts_special_session', [
  'special-nstc',
  'special-nlsc',
  'special-land',
  'special-national-park',
])
export const enum_abstracts_presentation_preference = pgEnum(
  'enum_abstracts_presentation_preference',
  ['oral', 'poster', 'either'],
)
export const enum_abstracts_review_status = pgEnum('enum_abstracts_review_status', [
  'pending',
  'accepted',
  'rejected',
  'revision',
])
export const enum_pages_hero_links_link_type = pgEnum('enum_pages_hero_links_link_type', [
  'custom',
  'reference',
])
export const enum_pages_hero_links_link_appearance = pgEnum(
  'enum_pages_hero_links_link_appearance',
  ['default', 'primary', 'secondary'],
)
export const enum_pages_hero_type = pgEnum('enum_pages_hero_type', [
  'none',
  'highImpact',
  'mediumImpact',
  'lowImpact',
])
export const enum_pages_status = pgEnum('enum_pages_status', ['draft', 'published'])
export const enum__pages_v_version_hero_links_link_type = pgEnum(
  'enum__pages_v_version_hero_links_link_type',
  ['custom', 'reference'],
)
export const enum__pages_v_version_hero_links_link_appearance = pgEnum(
  'enum__pages_v_version_hero_links_link_appearance',
  ['default', 'primary', 'secondary'],
)
export const enum__pages_v_version_hero_type = pgEnum('enum__pages_v_version_hero_type', [
  'none',
  'highImpact',
  'mediumImpact',
  'lowImpact',
])
export const enum__pages_v_version_status = pgEnum('enum__pages_v_version_status', [
  'draft',
  'published',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    gender: enum_users_gender('gender'),
    birthday: timestamp('birthday', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    phone: varchar('phone').notNull(),
    organization: varchar('organization').notNull(),
    jobTitle: varchar('job_title').notNull(),
    role: enum_users_role('role').notNull().default('user'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    _verified: boolean('_verified'),
    _verificationToken: varchar('_verificationtoken'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const news_related_files = pgTable(
  'news_related_files',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    type: enum_news_related_files_type('type').default('file'),
    label: varchar('label'),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
  },
  (columns) => [
    index('news_related_files_order_idx').on(columns._order),
    index('news_related_files_parent_id_idx').on(columns._parentID),
    index('news_related_files_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [news.id],
      name: 'news_related_files_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const news = pgTable(
  'news',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    showOnHomepage: boolean('show_on_homepage').default(false),
    category: enum_news_category('category').default('重要公告'),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    content: jsonb('content'),
    actionLink: varchar('action_link'),
    actionText: varchar('action_text').default('前往查看'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_news_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('news_slug_idx').on(columns.slug),
    index('news_updated_at_idx').on(columns.updatedAt),
    index('news_created_at_idx').on(columns.createdAt),
    index('news__status_idx').on(columns._status),
  ],
)

export const _news_v_version_related_files = pgTable(
  '_news_v_version_related_files',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    type: enum__news_v_version_related_files_type('type').default('file'),
    label: varchar('label'),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_news_v_version_related_files_order_idx').on(columns._order),
    index('_news_v_version_related_files_parent_id_idx').on(columns._parentID),
    index('_news_v_version_related_files_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_news_v.id],
      name: '_news_v_version_related_files_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _news_v = pgTable(
  '_news_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => news.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_showOnHomepage: boolean('version_show_on_homepage').default(false),
    version_category: enum__news_v_version_category('version_category').default('重要公告'),
    version_publishedDate: timestamp('version_published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_content: jsonb('version_content'),
    version_actionLink: varchar('version_action_link'),
    version_actionText: varchar('version_action_text').default('前往查看'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__news_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_news_v_parent_idx').on(columns.parent),
    index('_news_v_version_version_slug_idx').on(columns.version_slug),
    index('_news_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_news_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_news_v_version_version__status_idx').on(columns.version__status),
    index('_news_v_created_at_idx').on(columns.createdAt),
    index('_news_v_updated_at_idx').on(columns.updatedAt),
    index('_news_v_latest_idx').on(columns.latest),
  ],
)

export const registrations = pgTable(
  'registrations',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    ticketType: enum_registrations_ticket_type('ticket_type').notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    paymentStatus: enum_registrations_payment_status('payment_status').notNull().default('pending'),
    contactAddress: varchar('contact_address').notNull(),
    participantRole: enum_registrations_participant_role('participant_role').notNull(),
    participantRoleOther: varchar('participant_role_other'),
    presentationType: enum_registrations_presentation_type('presentation_type'),
    paymentAccountLast5: varchar('payment_account_last5').notNull(),
    paymentDate: timestamp('payment_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    invoiceTitle: varchar('invoice_title'),
    invoiceTaxId: varchar('invoice_tax_id'),
    mealDay1: enum_registrations_meal_day1('meal_day1').notNull(),
    mealDay2: enum_registrations_meal_day2('meal_day2').notNull(),
    banquet: enum_registrations_banquet('banquet').notNull(),
    dietaryPreference: enum_registrations_dietary_preference('dietary_preference'),
    dietaryOther: varchar('dietary_other'),
    remarks: varchar('remarks'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('registrations_user_idx').on(columns.user),
    index('registrations_updated_at_idx').on(columns.updatedAt),
    index('registrations_created_at_idx').on(columns.createdAt),
  ],
)

export const abstracts_authors = pgTable(
  'abstracts_authors',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    affiliation: varchar('affiliation').notNull(),
    email: varchar('email').notNull(),
    isCorresponding: boolean('is_corresponding').default(false),
  },
  (columns) => [
    index('abstracts_authors_order_idx').on(columns._order),
    index('abstracts_authors_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [abstracts.id],
      name: 'abstracts_authors_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const abstracts = pgTable(
  'abstracts',
  {
    id: serial('id').primaryKey(),
    submitter: integer('submitter_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').notNull(),
    subTopic: enum_abstracts_sub_topic('sub_topic'),
    specialSession: enum_abstracts_special_session('special_session'),
    isStudent: boolean('is_student').default(false),
    applyStudentAward: boolean('apply_student_award').default(false),
    fullPaper: integer('full_paper_id').references(() => full_papers.id, {
      onDelete: 'set null',
    }),
    abstract: varchar('abstract').notNull(),
    keywords: varchar('keywords').notNull(),
    presentationPreference: enum_abstracts_presentation_preference('presentation_preference'),
    reviewStatus: enum_abstracts_review_status('review_status').notNull().default('pending'),
    reviewComments: varchar('review_comments'),
    assignedReviewer: integer('assigned_reviewer_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('abstracts_submitter_idx').on(columns.submitter),
    index('abstracts_full_paper_idx').on(columns.fullPaper),
    index('abstracts_assigned_reviewer_idx').on(columns.assignedReviewer),
    index('abstracts_updated_at_idx').on(columns.updatedAt),
    index('abstracts_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_hero_links = pgTable(
  'pages_hero_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    link_type: enum_pages_hero_links_link_type('link_type').default('reference'),
    link_url: varchar('link_url'),
    link_label: varchar('link_label'),
    link_appearance: enum_pages_hero_links_link_appearance('link_appearance').default('default'),
  },
  (columns) => [
    index('pages_hero_links_order_idx').on(columns._order),
    index('pages_hero_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_hero_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    hero_type: enum_pages_hero_type('hero_type').default('lowImpact'),
    hero_richText: jsonb('hero_rich_text'),
    hero_media: integer('hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_hero_hero_media_idx').on(columns.hero_media),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
    index('pages__status_idx').on(columns._status),
  ],
)

export const pages_rels = pgTable(
  'pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    pagesID: integer('pages_id'),
    newsID: integer('news_id'),
  },
  (columns) => [
    index('pages_rels_order_idx').on(columns.order),
    index('pages_rels_parent_idx').on(columns.parent),
    index('pages_rels_path_idx').on(columns.path),
    index('pages_rels_pages_id_idx').on(columns.pagesID),
    index('pages_rels_news_id_idx').on(columns.newsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [pages.id],
      name: 'pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'pages_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['newsID']],
      foreignColumns: [news.id],
      name: 'pages_rels_news_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v_version_hero_links = pgTable(
  '_pages_v_version_hero_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    link_type: enum__pages_v_version_hero_links_link_type('link_type').default('reference'),
    link_url: varchar('link_url'),
    link_label: varchar('link_label'),
    link_appearance:
      enum__pages_v_version_hero_links_link_appearance('link_appearance').default('default'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_version_hero_links_order_idx').on(columns._order),
    index('_pages_v_version_hero_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_version_hero_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _pages_v = pgTable(
  '_pages_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => pages.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_hero_type: enum__pages_v_version_hero_type('version_hero_type').default('lowImpact'),
    version_hero_richText: jsonb('version_hero_rich_text'),
    version_hero_media: integer('version_hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__pages_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_pages_v_parent_idx').on(columns.parent),
    index('_pages_v_version_version_slug_idx').on(columns.version_slug),
    index('_pages_v_version_hero_version_hero_media_idx').on(columns.version_hero_media),
    index('_pages_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_pages_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_pages_v_version_version__status_idx').on(columns.version__status),
    index('_pages_v_created_at_idx').on(columns.createdAt),
    index('_pages_v_updated_at_idx').on(columns.updatedAt),
    index('_pages_v_latest_idx').on(columns.latest),
  ],
)

export const _pages_v_rels = pgTable(
  '_pages_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    pagesID: integer('pages_id'),
    newsID: integer('news_id'),
  },
  (columns) => [
    index('_pages_v_rels_order_idx').on(columns.order),
    index('_pages_v_rels_parent_idx').on(columns.parent),
    index('_pages_v_rels_path_idx').on(columns.path),
    index('_pages_v_rels_pages_id_idx').on(columns.pagesID),
    index('_pages_v_rels_news_id_idx').on(columns.newsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: '_pages_v_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['newsID']],
      foreignColumns: [news.id],
      name: '_pages_v_rels_news_fk',
    }).onDelete('cascade'),
  ],
)

export const full_papers = pgTable(
  'full_papers',
  {
    id: serial('id').primaryKey(),
    uploadedBy: integer('uploaded_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('full_papers_uploaded_by_idx').on(columns.uploadedBy),
    index('full_papers_updated_at_idx').on(columns.updatedAt),
    index('full_papers_created_at_idx').on(columns.createdAt),
    uniqueIndex('full_papers_filename_idx').on(columns.filename),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    newsID: integer('news_id'),
    registrationsID: integer('registrations_id'),
    abstractsID: integer('abstracts_id'),
    pagesID: integer('pages_id'),
    'full-papersID': integer('full_papers_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_news_id_idx').on(columns.newsID),
    index('payload_locked_documents_rels_registrations_id_idx').on(columns.registrationsID),
    index('payload_locked_documents_rels_abstracts_id_idx').on(columns.abstractsID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_full_papers_id_idx').on(columns['full-papersID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['newsID']],
      foreignColumns: [news.id],
      name: 'payload_locked_documents_rels_news_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['registrationsID']],
      foreignColumns: [registrations.id],
      name: 'payload_locked_documents_rels_registrations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['abstractsID']],
      foreignColumns: [abstracts.id],
      name: 'payload_locked_documents_rels_abstracts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['full-papersID']],
      foreignColumns: [full_papers.id],
      name: 'payload_locked_documents_rels_full_papers_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const abstracts_settings = pgTable('abstracts_settings', {
  id: serial('id').primaryKey(),
  submissionOpen: boolean('submission_open').default(true),
  reviewResultPublished: boolean('review_result_published').default(false),
  submissionDeadline: timestamp('submission_deadline', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
  fullPaperSubmissionOpen: boolean('full_paper_submission_open').default(true),
  fullPaperDeadline: timestamp('full_paper_deadline', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_news_related_files = relations(news_related_files, ({ one }) => ({
  _parentID: one(news, {
    fields: [news_related_files._parentID],
    references: [news.id],
    relationName: 'relatedFiles',
  }),
  file: one(media, {
    fields: [news_related_files.file],
    references: [media.id],
    relationName: 'file',
  }),
}))
export const relations_news = relations(news, ({ many }) => ({
  relatedFiles: many(news_related_files, {
    relationName: 'relatedFiles',
  }),
}))
export const relations__news_v_version_related_files = relations(
  _news_v_version_related_files,
  ({ one }) => ({
    _parentID: one(_news_v, {
      fields: [_news_v_version_related_files._parentID],
      references: [_news_v.id],
      relationName: 'version_relatedFiles',
    }),
    file: one(media, {
      fields: [_news_v_version_related_files.file],
      references: [media.id],
      relationName: 'file',
    }),
  }),
)
export const relations__news_v = relations(_news_v, ({ one, many }) => ({
  parent: one(news, {
    fields: [_news_v.parent],
    references: [news.id],
    relationName: 'parent',
  }),
  version_relatedFiles: many(_news_v_version_related_files, {
    relationName: 'version_relatedFiles',
  }),
}))
export const relations_registrations = relations(registrations, ({ one }) => ({
  user: one(users, {
    fields: [registrations.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_abstracts_authors = relations(abstracts_authors, ({ one }) => ({
  _parentID: one(abstracts, {
    fields: [abstracts_authors._parentID],
    references: [abstracts.id],
    relationName: 'authors',
  }),
}))
export const relations_abstracts = relations(abstracts, ({ one, many }) => ({
  submitter: one(users, {
    fields: [abstracts.submitter],
    references: [users.id],
    relationName: 'submitter',
  }),
  authors: many(abstracts_authors, {
    relationName: 'authors',
  }),
  fullPaper: one(full_papers, {
    fields: [abstracts.fullPaper],
    references: [full_papers.id],
    relationName: 'fullPaper',
  }),
  assignedReviewer: one(users, {
    fields: [abstracts.assignedReviewer],
    references: [users.id],
    relationName: 'assignedReviewer',
  }),
}))
export const relations_pages_hero_links = relations(pages_hero_links, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_hero_links._parentID],
    references: [pages.id],
    relationName: 'hero_links',
  }),
}))
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: '_rels',
  }),
  pagesID: one(pages, {
    fields: [pages_rels.pagesID],
    references: [pages.id],
    relationName: 'pages',
  }),
  newsID: one(news, {
    fields: [pages_rels.newsID],
    references: [news.id],
    relationName: 'news',
  }),
}))
export const relations_pages = relations(pages, ({ one, many }) => ({
  hero_media: one(media, {
    fields: [pages.hero_media],
    references: [media.id],
    relationName: 'hero_media',
  }),
  hero_links: many(pages_hero_links, {
    relationName: 'hero_links',
  }),
  _rels: many(pages_rels, {
    relationName: '_rels',
  }),
}))
export const relations__pages_v_version_hero_links = relations(
  _pages_v_version_hero_links,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_version_hero_links._parentID],
      references: [_pages_v.id],
      relationName: 'version_hero_links',
    }),
  }),
)
export const relations__pages_v_rels = relations(_pages_v_rels, ({ one }) => ({
  parent: one(_pages_v, {
    fields: [_pages_v_rels.parent],
    references: [_pages_v.id],
    relationName: '_rels',
  }),
  pagesID: one(pages, {
    fields: [_pages_v_rels.pagesID],
    references: [pages.id],
    relationName: 'pages',
  }),
  newsID: one(news, {
    fields: [_pages_v_rels.newsID],
    references: [news.id],
    relationName: 'news',
  }),
}))
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: 'parent',
  }),
  version_hero_media: one(media, {
    fields: [_pages_v.version_hero_media],
    references: [media.id],
    relationName: 'version_hero_media',
  }),
  version_hero_links: many(_pages_v_version_hero_links, {
    relationName: 'version_hero_links',
  }),
  _rels: many(_pages_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_full_papers = relations(full_papers, ({ one }) => ({
  uploadedBy: one(users, {
    fields: [full_papers.uploadedBy],
    references: [users.id],
    relationName: 'uploadedBy',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    newsID: one(news, {
      fields: [payload_locked_documents_rels.newsID],
      references: [news.id],
      relationName: 'news',
    }),
    registrationsID: one(registrations, {
      fields: [payload_locked_documents_rels.registrationsID],
      references: [registrations.id],
      relationName: 'registrations',
    }),
    abstractsID: one(abstracts, {
      fields: [payload_locked_documents_rels.abstractsID],
      references: [abstracts.id],
      relationName: 'abstracts',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    'full-papersID': one(full_papers, {
      fields: [payload_locked_documents_rels['full-papersID']],
      references: [full_papers.id],
      relationName: 'full-papers',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_abstracts_settings = relations(abstracts_settings, () => ({}))

type DatabaseSchema = {
  enum_users_gender: typeof enum_users_gender
  enum_users_role: typeof enum_users_role
  enum_news_related_files_type: typeof enum_news_related_files_type
  enum_news_category: typeof enum_news_category
  enum_news_status: typeof enum_news_status
  enum__news_v_version_related_files_type: typeof enum__news_v_version_related_files_type
  enum__news_v_version_category: typeof enum__news_v_version_category
  enum__news_v_version_status: typeof enum__news_v_version_status
  enum_registrations_ticket_type: typeof enum_registrations_ticket_type
  enum_registrations_payment_status: typeof enum_registrations_payment_status
  enum_registrations_participant_role: typeof enum_registrations_participant_role
  enum_registrations_presentation_type: typeof enum_registrations_presentation_type
  enum_registrations_meal_day1: typeof enum_registrations_meal_day1
  enum_registrations_meal_day2: typeof enum_registrations_meal_day2
  enum_registrations_banquet: typeof enum_registrations_banquet
  enum_registrations_dietary_preference: typeof enum_registrations_dietary_preference
  enum_abstracts_sub_topic: typeof enum_abstracts_sub_topic
  enum_abstracts_special_session: typeof enum_abstracts_special_session
  enum_abstracts_presentation_preference: typeof enum_abstracts_presentation_preference
  enum_abstracts_review_status: typeof enum_abstracts_review_status
  enum_pages_hero_links_link_type: typeof enum_pages_hero_links_link_type
  enum_pages_hero_links_link_appearance: typeof enum_pages_hero_links_link_appearance
  enum_pages_hero_type: typeof enum_pages_hero_type
  enum_pages_status: typeof enum_pages_status
  enum__pages_v_version_hero_links_link_type: typeof enum__pages_v_version_hero_links_link_type
  enum__pages_v_version_hero_links_link_appearance: typeof enum__pages_v_version_hero_links_link_appearance
  enum__pages_v_version_hero_type: typeof enum__pages_v_version_hero_type
  enum__pages_v_version_status: typeof enum__pages_v_version_status
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  news_related_files: typeof news_related_files
  news: typeof news
  _news_v_version_related_files: typeof _news_v_version_related_files
  _news_v: typeof _news_v
  registrations: typeof registrations
  abstracts_authors: typeof abstracts_authors
  abstracts: typeof abstracts
  pages_hero_links: typeof pages_hero_links
  pages: typeof pages
  pages_rels: typeof pages_rels
  _pages_v_version_hero_links: typeof _pages_v_version_hero_links
  _pages_v: typeof _pages_v
  _pages_v_rels: typeof _pages_v_rels
  full_papers: typeof full_papers
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  abstracts_settings: typeof abstracts_settings
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_news_related_files: typeof relations_news_related_files
  relations_news: typeof relations_news
  relations__news_v_version_related_files: typeof relations__news_v_version_related_files
  relations__news_v: typeof relations__news_v
  relations_registrations: typeof relations_registrations
  relations_abstracts_authors: typeof relations_abstracts_authors
  relations_abstracts: typeof relations_abstracts
  relations_pages_hero_links: typeof relations_pages_hero_links
  relations_pages_rels: typeof relations_pages_rels
  relations_pages: typeof relations_pages
  relations__pages_v_version_hero_links: typeof relations__pages_v_version_hero_links
  relations__pages_v_rels: typeof relations__pages_v_rels
  relations__pages_v: typeof relations__pages_v
  relations_full_papers: typeof relations_full_papers
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_abstracts_settings: typeof relations_abstracts_settings
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
