/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    registrations: Registration;
    abstracts: Abstract;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    abstracts: AbstractsSelect<false> | AbstractsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'abstracts-settings': AbstractsSetting;
  };
  globalsSelect: {
    'abstracts-settings': AbstractsSettingsSelect<false> | AbstractsSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  gender?: ('male' | 'female' | 'other') | null;
  birthday: string;
  phone: string;
  organization: string;
  jobTitle: string;
  role: 'admin' | 'user' | 'reviewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * 這會變成網址的一部分,例如 /news/call-for-papers
   */
  slug: string;
  /**
   * 勾選後會顯示在首頁最新消息區(最多3則)
   */
  showOnHomepage?: boolean | null;
  category: '重要公告' | '徵稿資訊' | '會議議程' | '註冊報名' | '榮譽榜單' | '一般消息';
  publishedDate: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 可在此上傳 PDF、Word 檔或加入相關連結
   */
  relatedFiles?:
    | {
        type?: ('file' | 'link') | null;
        label: string;
        file?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 適合放最重要的行動呼籲,如「前往報名表單」
   */
  actionLink?: string | null;
  actionText?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  user?: (number | null) | User;
  ticketType: 'early-bird-student' | 'early-bird-regular' | 'standard-student' | 'standard-regular';
  amount: number;
  paymentStatus: 'pending' | 'paid' | 'failed';
  contactAddress: string;
  participantRole: 'presenter' | 'keynote' | 'host' | 'discussant' | 'attendee' | 'staff' | 'vip' | 'other';
  participantRoleOther?: string | null;
  presentationType?: ('oral' | 'poster' | 'both' | 'none') | null;
  paymentAccountLast5: string;
  paymentDate: string;
  invoiceTitle?: string | null;
  invoiceTaxId?: string | null;
  mealDay1: 'yes' | 'no';
  mealDay2: 'yes' | 'no';
  banquet: 'yes' | 'no';
  dietaryPreference?: ('regular' | 'vegetarian' | 'other') | null;
  dietaryOther?: string | null;
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts".
 */
export interface Abstract {
  id: number;
  submitter: number | User;
  title: string;
  authors: {
    name: string;
    affiliation: string;
    email: string;
    isCorresponding?: boolean | null;
    id?: string | null;
  }[];
  /**
   * 特別論壇投稿可留空
   */
  subTopic?:
    | (
        | 'topic-1'
        | 'topic-2'
        | 'topic-3'
        | 'topic-4'
        | 'topic-5'
        | 'topic-6'
        | 'topic-7'
        | 'topic-8'
        | 'topic-9'
        | 'topic-10'
      )
    | null;
  /**
   * 如為特別論壇邀請文章，請在此選擇；一般投稿請留空
   */
  specialSession?: ('special-nstc' | 'special-nlsc' | 'special-land' | 'special-national-park') | null;
  isStudent?: boolean | null;
  /**
   * 勾選後需上傳全文（PDF 或 DOCX，10MB 以內）
   */
  applyStudentAward?: boolean | null;
  /**
   * 請上傳 PDF 或 DOCX 格式，檔案大小限 10MB 以內
   */
  fullTextFile?: (number | null) | Media;
  /**
   * 請輸入 250 字以內的中英文摘要
   */
  abstract: string;
  /**
   * 請以逗號分隔，至少填寫 3 個關鍵字，例如：衛星定位, GNSS, 導航
   */
  keywords: string;
  /**
   * 實際發表形式由大會排程決定，此為偏好登記
   */
  presentationPreference?: ('oral' | 'poster' | 'either') | null;
  reviewStatus: 'pending' | 'accepted' | 'rejected' | 'revision';
  /**
   * 此評語在大會發布審查結果後，會顯示給投稿人
   */
  reviewComments?: string | null;
  /**
   * 只能選擇 role=reviewer 的使用者
   */
  assignedReviewer?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    media?: (number | null) | Media;
    links?:
      | {
          link: {
            type?: ('custom' | 'reference') | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'news';
                  value: number | News;
                } | null);
            url?: string | null;
            label: string;
            appearance?: ('default' | 'primary' | 'secondary') | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'abstracts';
        value: number | Abstract;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  gender?: T;
  birthday?: T;
  phone?: T;
  organization?: T;
  jobTitle?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showOnHomepage?: T;
  category?: T;
  publishedDate?: T;
  content?: T;
  relatedFiles?:
    | T
    | {
        type?: T;
        label?: T;
        file?: T;
        url?: T;
        id?: T;
      };
  actionLink?: T;
  actionText?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  user?: T;
  ticketType?: T;
  amount?: T;
  paymentStatus?: T;
  contactAddress?: T;
  participantRole?: T;
  participantRoleOther?: T;
  presentationType?: T;
  paymentAccountLast5?: T;
  paymentDate?: T;
  invoiceTitle?: T;
  invoiceTaxId?: T;
  mealDay1?: T;
  mealDay2?: T;
  banquet?: T;
  dietaryPreference?: T;
  dietaryOther?: T;
  remarks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts_select".
 */
export interface AbstractsSelect<T extends boolean = true> {
  submitter?: T;
  title?: T;
  authors?:
    | T
    | {
        name?: T;
        affiliation?: T;
        email?: T;
        isCorresponding?: T;
        id?: T;
      };
  subTopic?: T;
  specialSession?: T;
  isStudent?: T;
  applyStudentAward?: T;
  fullTextFile?: T;
  abstract?: T;
  keywords?: T;
  presentationPreference?: T;
  reviewStatus?: T;
  reviewComments?: T;
  assignedReviewer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        media?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts-settings".
 */
export interface AbstractsSetting {
  id: number;
  /**
   * 關閉後，前台投稿表單將顯示「投稿已截止」，使用者無法新增或修改投稿
   */
  submissionOpen?: boolean | null;
  /**
   * 勾選後，投稿人在「我的投稿」頁面將看到真實的審查結果（通過/未通過）與評語。建議在所有文章都有審查結果後再發布。
   */
  reviewResultPublished?: boolean | null;
  /**
   * 僅供顯示用，實際開關請用「開放摘要投稿」選項
   */
  submissionDeadline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts-settings_select".
 */
export interface AbstractsSettingsSelect<T extends boolean = true> {
  submissionOpen?: T;
  reviewResultPublished?: T;
  submissionDeadline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}